apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: org-docs
  description: Canonical Org Knowledge Base for the publishing platform demo
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: documentation
  lifecycle: production
  owner: team-backend
  system: publishing-platform
